# Generated by Django 4.1.4 on 2023-01-17 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('pergunta', models.CharField(max_length=40)),
                ('resposta', models.CharField(max_length=30)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questao.lista')),
            ],
        ),
    ]
